help_file = {
    "server": "Configure o mundo no qual o bot deve jogar",
    "server.server": "O endpoint do servidor a ser usado (o mundo)",
    "server.endpoint": "Endpoint do servidor a ser usado (a URL completa)",
    "server.server_on_twstats": "O servidor está listado no twstats.com?",
    "reporting": "Habilitar recursos avançados de relatórios",
    "reporting.enabled": "Habilitar o recurso de relatórios",
    "reporting.connection_string": "Pode ser do tipo file://filename ou mysql://user:password@host:port/database_name",
    "bot": "Definir variáveis de configuração global do bot",
    "bot.active_hours": "As horas em que o bot deve usar o active_delay (isso não impacta os horários de ataque)",
    "bot.delay_factor": "Fator de atraso a ser usado 5-7 segundos * fator de atraso (fatores muito baixos provavelmente causarão banimento)",
    "bot.active_delay": "Atraso em segundos a ser usado nos tempos ativos do bot",
    "bot.inactive_delay": "Atraso em segundos a ser usado nos tempos inativos do bot",
    "bot.inactive_still_active": "Inativo para impedir que o bot continue funcionando durante os tempos inativos",
    "bot.add_new_villages": "Adicionar automaticamente a configuração padrão da vila às vilas recém-conquistadas",
    "bot.village_name_template": "Modelo a ser usado para novas vilas, use {num} para definir o índice da configuração como nome",
    "bot.village_name_number_length": "O comprimento do número, menor será prefixado com zeros",
    "bot.auto_set_village_names": "Definir automaticamente os nomes das vilas",
    "bot.user_agent": "Defina isso como o agente do navegador que sua sessão está usando (caso contrário, pode causar banimento)",
    "building.manage_buildings": "Gerenciar automaticamente os edifícios",
    "building": "A criação automática de edifícios",
    "building.default": "O modelo padrão a ser usado, as configurações da vila substituem esta variável",
    "building.max_lookahead": "A quantidade máxima de itens na fila a verificar antes de parar",
    "building.max_queued_items": "Quantidade máxima de itens na fila, padrão: 2 premium: 5",
    "units": "Habilitar recrutamento automático de unidades",
    "units.recruit": "Recrutar unidades automaticamente",
    "units.upgrade": "Atualizar unidades automaticamente (somente para nível 1-3, 1-10 sistemas de ferreiro)",
    "units.default": "Modelo padrão para criação de unidades (templates/troops)",
    "units.batch_size": "Quantidade de unidades a tentar criar em uma única execução, aumente isso no final do jogo",
    "units.manage_defence": "Gerenciar defesa entre vilas (experimental)",
    "units.remove_manual_queued": "Remover entradas de recrutamento manual na fila",
    "units.randomize_unit_queue": "Aleatorizar a fila de unidades, permitindo uma maior variedade de unidades",
    "farms": "Farming automático de vilas próximas (bárbaras)",
    "farms.farm": "Habilitar farming automático",
    "farms.min_points": "Os pontos mínimos das vilas a serem atacadas (também verifica custom_farms)",
    "farms.max_points": "Os pontos máximos das vilas a serem atacadas (também verifica custom_farms)",
    "farms.find_player_owned": "Ataca automaticamente todas as vilas de jogadores (perigoso)",
    "farms.search_radius": "Raio máximo de vilas a serem atacadas (campos)",
    "farms.default_away_time": "Tempo padrão em segundos para dormir antes de atacar uma vila novamente",
    "farms.full_loot_away_time": "Tempo fora para vilas com grande ganho de recursos",
    "farms.low_loot_away_time": "Tempo fora para vilas com baixo ganho de recursos",
    "farms.max_farms": "A quantidade de vilas próximas a verificar",
    "farms.attack_higher_points": "Se habilitado, vilas com mais pontos do que a atual serão automaticamente ignoradas",
    "farms.force_scout_if_available": "Só atacará vilas que tenham sido atacadas antes ou que serão automaticamente exploradas",
    "farms.farm_scout_amount": "Define a quantidade de espiões usados para determinar se uma vila é segura para farming",
    "market": "Gerenciamento automático de trocas no mercado",
    "market.auto_trade": "Habilitar trocas automatizadas",
    "market.max_trade_duration": "Duração máxima das trocas (horas)",
    "market.auto_remove": "Remove automaticamente trocas existentes ou expiradas",
    "market.trade_multiplier": "Defina como verdadeiro se o mundo suportar razões de trocas desiguais",
    "market.trade_multiplier_value": "Valor do multiplicador (quanto menor, mais ganho)",
    "market.trade_max_per_hour": "A quantidade de trocas que o bot pode fazer em 1 hora",
    "world.knight_enabled": "O mundo tem cavaleiros habilitados",
    "world.flags_enabled": "Permite gerenciamento automático de bandeiras (atualização e defesa)",
    "world.quests_enabled": "O mundo tem missões habilitadas (o bot as concluirá automaticamente)",
    "world.trade_for_premium": "O mundo tem o mercado premium habilitado (fazer isso demais pode resultar em banimento)",
    "world.archers_enabled": "Os arqueiros/marchadores estão habilitados no mundo",
    "world.building_destruction_enabled": "Os aríetes/catapulta estão habilitados no mundo",
    "village_template": "O modelo padrão para vilas a serem usadas",
    "village.building": "Substituir modelo de construção",
    "village.units": "Substituir modelo de recrutamento/farming",
    "village.managed": "A vila deve ser gerenciada pelo bot",
    "village.scout_first": "A vila deve explorar vilas antes de fazer farming",
    "village.additional_farms": "Lista de vilas para incluir no processo de farming (não requer que find_player_owned esteja ativo)",
    "village.prioritize_building": "Não recrutar se o construtor não tiver recursos suficientes",
    "village.prioritize_snob": "Não recrutar se o snob não tiver recursos suficientes",
    "village.trade_for_premium": "Trocar recursos sobrando por pontos premium (requer que a opção global esteja habilitada)",
    "village.gather_enabled": "Usa unidades sobrando para coletar recursos adicionais se a opção estiver habilitada no mundo",
    "village.gather_selection": "A operação de coleta a ser realizada (devem ser desbloqueadas primeiro)",
    "village.snobs": "A quantidade de snobs a criar na vila atual",
    "village.evacuate_fragile_units_on_attack": "Evacuar automaticamente unidades frágeis (machado, snob) para vilas seguras próximas em caso de ataque",
    "village.support_others": "Permite o envio automático de apoio",
    "village.support_others_factor": "Fator de unidades a serem usadas na operação de apoio (somente defensivas)",
    "village.support_others_max_villages": "A quantidade máxima de vilas para enviar apoio (total 2 * 25% das tropas)",
    "village.request_support_on_attack": "Permite solicitação automática de unidades de apoio",
}

buildings = [
    "main",
    "barracks",
    "stable",
    "watchtower",
    "smith",
    "garage",
    "place",
    "statue",
    "market",
    "wood",
    "stone",
    "iron",
    "farm",
    "hide",
    "wall",
    "snob",
    "church",
]
